name: Node.js CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run build --if-present
      - name: upload dist
        env:
          ACCESSKEYID: ${{secrets.ACCESSKEYID}}
          ACCESSKEYSECRET: ${{secrets.ACCESSKEYSECRET}}
        run: node deploy
